D.trace hinzufügen
mgudemann/liascriptCourses pull request #6
Opened 2022-01-25 14:08 UTC by Mariuxdeangelo

Ein kleines beispiel für D.traace hinzufügen für debugging.

2022-01-25 14:33 UTC, Mariuxdeangelo commented
Ich habe hier noch ein Beispiel für D.trace unten angefügt. Ich denke, dass das noch ganz gut zu wissen wenn man mal nicht weiterkommt.

2022-01-25 15:13 UTC, mgudemann approved these changes

2022-01-25 15:13 UTC, mgudemann commented on krypto/krypto.md
> +Um eine Logausgabe zu einzelnen Schritten in der Anwendung zu bekommen kann man D.trace verwenden, welche "kontrolliert" seiteneffekte erzeugt, um eine Ausgabe im Terminal zu machen. (D.trace muss ex
```suggestion
Um eine Logausgabe zu einzelnen Schritten in der Anwendung zu bekommen kann man D.trace verwenden, welche "kontrolliert" Seiteneffekte erzeugt, um eine Ausgabe im Terminal zu machen (das Modul `Debug.Trace` muss dazu explizit importiert werden).
```

2022-01-25 15:14 UTC, mgudemann requested changes

2022-01-25 15:14 UTC, mgudemann commented on krypto/krypto.md
> +Um eine Logausgabe zu einzelnen Schritten in der Anwendung zu bekommen kann man D.trace verwenden, welche "kontrolliert" seiteneffekte erzeugt, um eine Ausgabe im Terminal zu machen. (D.trace muss ex
bitte noch dies hier hinzufügen

2022-01-25 16:55 UTC, Mariuxdeangelo commented
So, sollte jetzt passen. Hätte ich nochmal lesen sollen, bevor ich es aus meinen Notizen rauskopiere. 😅

2022-01-26 06:15 UTC, mgudemann approved these changes

2022-01-26 06:15 UTC, merged